# Generated by Django 6.0 on 2026-02-10 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polyclinics', '0001_initial'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(verbose_name='Keluhan')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, verbose_name='Tekanan Darah')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Suhu (°C)')),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Detak Jantung')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Berat Badan (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tinggi Badan (cm)')),
                ('urgency_level', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('critical', 'Kritis')], default='low', max_length=20, verbose_name='Tingkat Urgensi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Petugas')),
                ('referred_polyclinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polyclinics.polyclinic', verbose_name='Poli Tujuan')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage', to='registrations.registration', verbose_name='Registrasi')),
            ],
            options={
                'verbose_name': 'Triage',
                'verbose_name_plural': 'Triage',
                'db_table': 'triages',
                'ordering': ['-created_at'],
            },
        ),
    ]
