# Generated by Django 6.0 on 2026-02-10 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Obat')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stok')),
                ('unit', models.CharField(default='tablet', max_length=30, verbose_name='Satuan')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Harga')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obat',
                'verbose_name_plural': 'Obat',
                'db_table': 'medicines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100, verbose_name='Dosis')),
                ('quantity', models.PositiveIntegerField(verbose_name='Jumlah')),
                ('instructions', models.TextField(blank=True, verbose_name='Aturan Pakai')),
                ('is_dispensed', models.BooleanField(default=False, verbose_name='Sudah Diserahkan')),
                ('dispensed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Penyerahan')),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diserahkan Oleh')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='examinations.examination', verbose_name='Pemeriksaan')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine', verbose_name='Obat')),
            ],
            options={
                'verbose_name': 'Resep',
                'verbose_name_plural': 'Resep',
                'db_table': 'prescriptions',
            },
        ),
    ]
