# Generated by Django 6.0 on 2026-02-10 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.PositiveIntegerField(verbose_name='No. Antrian')),
                ('status', models.CharField(choices=[('waiting_triage', 'Menunggu Triage'), ('in_triage', 'Sedang Triage'), ('waiting_exam', 'Menunggu Pemeriksaan'), ('in_exam', 'Sedang Diperiksa'), ('waiting_pharmacy', 'Menunggu Farmasi'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='waiting_triage', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='patients.patient', verbose_name='Pasien')),
            ],
            options={
                'verbose_name': 'Registrasi',
                'verbose_name_plural': 'Registrasi',
                'db_table': 'registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
