# Generated by Django 6.0 on 2026-02-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record_number', models.CharField(max_length=20, unique=True, verbose_name='No. Rekam Medis')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('birth_date', models.DateField(verbose_name='Tanggal Lahir')),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10, verbose_name='Jenis Kelamin')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('phone', models.CharField(max_length=20, verbose_name='No. Telepon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pasien',
                'verbose_name_plural': 'Pasien',
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
