# Generated by Django 6.0 on 2026-02-10 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='Diagnosis')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('treatment', models.TextField(blank=True, verbose_name='Tindakan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='doctors.doctor', verbose_name='Dokter')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examination', to='registrations.registration', verbose_name='Registrasi')),
            ],
            options={
                'verbose_name': 'Pemeriksaan',
                'verbose_name_plural': 'Pemeriksaan',
                'db_table': 'examinations',
                'ordering': ['-created_at'],
            },
        ),
    ]
